### ISSUE TITLE
Can't follow edge

### ISSUE THREAD

**Issue by matteyu** [marcomusy/vedo#132]
hi @marcomusy ,

I was taking a look at the cutWithPointLoop example and was wondering if it's possible to use that to **extract a portion of a mesh by xyz coordinates**?

something like this:

```
pts = Points([
    (19.04911645928067,-4.525300712179527,-10.071028860917263),
    (-20.421714455134765,-4.115338049591636,-9.55261519907026),
    (-20.470641773509726, -47.05823801668263, 0.37549320005188497),
    (19.411675239348407, -47.145670876391186, -0.37549337178984604),
], r=12)

scut = s.clone().c('blue').alpha(0.7).cutWithPointLoop(pts, invert=True)

show(scut, pts)
```

I'm basically trying to extract a square shape portion off a mesh object (.obj) and trying to save the extracted portion into a .stl file.  But when I try to do the extraction, I keep getting a "Can't follow edge" error.  

Any information would be greatly appreciated! thanks

**Comment by marcomusy** [comment]
Hi Matt, I cannot reproduce the error message because you dont show the complete code.
To extract a part of a mesh in xyz you can either use `mesh.cutWithPlane()` (multiple times) or even `mesh.cutWithMesh()`:
```python
from vtkplotter import *

s = Sphere(r=1).alpha(0.5).lw(0.1)
c= Cube(side=1).scale([0.5,1,1]).x(0.9).alpha(0.2).lw(0.1)
cut_s = s.clone().cutWithMesh(c)
show([(s,c), cut_s], N=2, axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/80548097-56b75800-89ba-11ea-8d01-6e9fa4d939e8.png)

Alternatively you can find the closest points on the mesh to your set of points in space and use those to cut the mesh with `cutWithPointLoop()`.

**Comment by matteyu** [comment]
Thank you for your help @marcomusy!  Your snippet gave me inspiration to solve my problem.

On another note, does the library support Orthographic projection view for the camera?  Is there an example I can look at?

Thank you for your help!

**Comment by marcomusy** [comment]
You're welcome! Yes, just add:
```python
from vtkplotter import settings

settings.useParallelProjection=True

#  ...
```

**Comment by milaganv2cloud** [comment]
Thank you for the quick reply @marcomusy! really appreciate it.

This is becoming a little bit of a tangent but i've tried running the library in a windows setup on parallels VM.  It does not work.  I suspect it's because parallels only support OpenGL 2.

I notice that when i'm trying to render a window, it's looking for OpenGL 3.  Would there be a way to change which OpenGL version the library uses? perhaps this is more of a VTK issue?

**Comment by matteyu** [comment]
Thank you for the quick reply @marcomusy! really appreciate it.

This is becoming a little bit of a tangent but i've tried running the library in a windows setup on parallels VM. It does not work. I suspect it's because parallels only support OpenGL 2.

I notice that when i'm trying to render a window, it's looking for OpenGL 3. Would there be a way to change which OpenGL version the library uses? perhaps this is more of a VTK issue?

**Comment by marcomusy** [comment]
Hi Matt, yes I'm afraid i'm not familiar enough with the opengl versions, you may try to ask in the https://discourse.vtk.org/ forum..
