### ISSUE TITLE
Boolean example

### ISSUE THREAD

**Issue by pempmu** [marcomusy/vedo#158]
Hi everyone,

I have a question regarding one of the capabilities shown in the example galery:

![image](https://user-images.githubusercontent.com/63414624/84246954-a8014e00-ab07-11ea-92e6-6a4ad92422ec.png)

I could not find more detailed information on the Boolean operation between 3d meshes. My first question is, on which geometrical kernel is vtkplotter relying to perform this operation?

Does anyone know if the boolean between two unstructured triangle meshes (mesh origianly coming from a point cloud + delaunay triangulation) would work?

Thanks in advance!

**Comment by marcomusy** [comment]
Hi @pempmu 
the example works with the `vtkBooleanOperationPolyDataFilter` class [here](https://vtk.org/doc/nightly/html/classvtkBooleanOperationPolyDataFilter.html), so in principle it only works with polygonal data as input.

Maybe you can do something different: extract the outer surface of one tetrahedral mesh and use it to cut the other:
`pip install -U git+https://github.com/marcomusy/vtkplotter.git`

check out this example, type:
`vtkplotter -ir tet_cutmesh1`

![image](https://user-images.githubusercontent.com/32848391/82767107-2631d500-9e25-11ea-967c-42558f98f721.jpg)

instead of the sphere you would use
`outermesh = geometry(my_other_ugrid)`
