### ISSUE TITLE
Color meshes using same colorBar

### ISSUE THREAD

**Issue by jsanchez679** [marcomusy/vedo#159]
Hi @marcomusy!
Hope this message finds you well. 
I have been using the vtkplotter function "distancetomesh" to assign colormaps to different meshes, but I would like to unify the colorbar for all of them in order to plot them in the same plot and be able to compare distances... I have been trying different things, but none have worked yet. Is there a way this can be done? 

Hope to hear from you soon!
Juliana

**Comment by marcomusy** [comment]
Hi @jsanchez679 ,
have you already tried using `vmin` and `vmax` ? As in:
https://github.com/marcomusy/vtkplotter/blob/master/vtkplotter/examples/basic/mesh_sharemap.py

Another way could be using:
`mesh.mapper().SetScalarRange(x0,x1)`

**Comment by jsanchez679** [comment]
Hi Marco!
Thanks for your reply!
Related to this last question, is there a way you can keep the colorcodes in a mesh when you cut it using another mesh? 
And is there a way you can keep at once all the different cuts of a mesh as independent meshes when you cut it? 

Thanks in advance! 
Juliana

**Comment by marcomusy** [comment]
Hi Juliana, 

> is there a way you can keep the colorcodes in a mesh when you cut it using another mesh?

yes - but there is a small bug which i already fixed in my local version, i will push it asap :) thanks for drawing my attention to it.

>  is there a way you can keep at once all the different cuts of a mesh as independent meshes when you cut it?

yes - that's very easy: just use `mesh.clone()`

E.g.

```python
from vedo import *

man1 = load(datadir+"man.vtk")
scals = man1.points()[:, 2] * 5 + 27

man1.pointColors(scals, cmap="jet", vmin=18, vmax=44)

s = Sphere().wireframe()
cman1 = man1.clone().cutWithMesh(s)

show([(s,man1), cman1], N=2, axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/85715569-e2641100-b6eb-11ea-94ea-9e875edd0537.png)

(this is not yet fixed in the master, so if you run it you'll probably get a solid blue mesh)
