### ISSUE TITLE
Basic/Boolean example clipping issue

### ISSUE THREAD

**Issue by Petrox** [marcomusy/vedo#205]
When rotating the double sphere in a way that the axis between the spheres is parallel with the centerline of the camera, then parts of the closer sphere becomes invisible (maybe behind the camera surface) and a hole appears.

cloned https://github.com/marcomusy/vedo/commit/17196b46b3943bfbb982f2de0787e277a3cac56a to a win10, example run with 3.8.5

![image](https://user-images.githubusercontent.com/3036509/92312992-af30de80-efc6-11ea-910f-a4b3c86fae73.png)

**Comment by marcomusy** [comment]
That's due to the clipping range of the camera - because the objects have very different sizes.
Try click on any renderer and press `r` to reset the camera.

A way to fix this programmatically is to specify the clipping range in your python script by cut&paste the output lines which you can get by pressing `C` (shift-c).

**Comment by Petrox** [comment]
Yes, I was looking for the word clipping... 

I'm not impacted by this, I just wanted to report the small hidden issue in the example code as I'm sure no one really tests them longer than 5 secs. 

This is a very low prio minor finding.

**Comment by marcomusy** [comment]
cool thanks for reporting!
