### ISSUE TITLE
colours in html export

### ISSUE THREAD

**Issue by yulint** [marcomusy/vedo#206]
Hi,

I have a scene composed of many tubes, each assigned different colours (the c of each tube is a list of colours), spheres, and a mesh (see below). The plotting looks great and I would like to keep the aesthetics in a shareable .html file. But when I export this to .html, the colours are completely changed, in a seemingly random (?) manner - is there a fix for this, or is this not compatible with html exporting? 
(The colour scale bar is also very different, although I have to say that I had manually created my scale bar, modifying the inbuilt vedo scale bar function)

in python plotter:
![image](https://user-images.githubusercontent.com/43373973/92603695-84d17080-f2a7-11ea-8232-53645d3409c0.png)

in html:
![image](https://user-images.githubusercontent.com/43373973/92603638-708d7380-f2a7-11ea-988f-c2ece97e94b5.png)

Also, it seems that Text2Ds are not compatible with html exports, there a couple of text labels I had to remove for this to work (error was: 'vtkmodules.vtkRenderingCore.vtkActor2D' object has no attribute 'filename'). Is there also a quick fix for this?

Thank you very much!

**Comment by marcomusy** [comment]
Hi @yulint - sorry for the very late reply - unfortunately the html generation has lots of limitations due to the `k3d` interface, I'm surprised that the scalarbar doesn't work, does this jupyter notebook work for you?

https://github.com/marcomusy/vedo/blob/master/notebooks/basic/sphere.ipynb

![image](https://user-images.githubusercontent.com/32848391/93255497-4f8ebc00-f79a-11ea-86c5-0e26c857e7db.png)

I fixed the `filename` bug thanks for spotting it.
