### ISSUE TITLE
How to show chinese character?

### ISSUE THREAD

**Issue by NeuZhangQiang** [marcomusy/vedo#245]
I find vedo can not show chinese character. 

For example, the following code can correctly show the english character 'cube':

```
from vedo import *
c = Cube()
show(c, 'cube')
```
![image](https://user-images.githubusercontent.com/62534955/99036138-10bf8b80-25bc-11eb-926e-a7127c8c5f86.png)

However, it can not show the chinese character '立方体'. 立方体 is the chinese translate of cube.

```
from vedo import *
c = Cube()
show(c, '立方体')
```
![image](https://user-images.githubusercontent.com/62534955/99036232-3d73a300-25bc-11eb-815b-1f2810f49fad.png)

**Comment by marcomusy** [comment]
This happens because the default font is "Normografo". Chinese chars are supported in "LogoType" font only (this is a large file which is downloaded on the fly from [here](https://vedo.embl.es/fonts/)).
```python
from vedo import *
c = Cube()
t2d = Text2D('cube (立方体)', font='LogoType')
t3d = Text('cube (立方体)', font='LogoType', s=0.05, c='b').z(0.6)
show(c, t2d, t3d)
```
![image](https://user-images.githubusercontent.com/32848391/99058234-34bfa480-259d-11eb-954b-08b7f47892f8.png)
