### ISSUE TITLE
Render FPS

### ISSUE THREAD

**Issue by FedeClaudi** [marcomusy/vedo#318]
Hi Marco, 

Is there a way to get the FPS with which a rendering is updated? I'm trying to set up some benchmarks for brainrender and this would be very valuable information. If there's no built in FPS count in vedo/vtk, is there a hook for a custom callback function at each window refresh?

**Comment by marcomusy** [comment]
I've been playing a bit with the rendering time provided by a vtk method but it seems to produce contradictory results:
```python
from vedo import *
import numpy as np

n = 500
s = Sphere(r=0.02, res=100)
print('points:', s.NPoints()*n, ' cells:', s.NCells()*n)
sps = [s.clone().pos(v).c(v) for v in np.random.rand(n,3)]
plt = show(sps, axes=1, interactive=0)

pb = ProgressBar(0, 100)
# note that what follows has nothing to do with vedo
fpss = []
for i in pb.range():
    # plt.allowInteraction() # vedo
    # plt.render(resetcam=0) # vedo

    plt.window.Render()  # pure vtk
    plt.camera.Elevation(0.1)

    fps = 1/plt.renderer.GetLastRenderTimeInSeconds()
    fpss.append(fps)
    pb.print(int(fps))

print('vtk mean fps:', np.mean(np.array(fpss)))
```
(vtk 8.1.2)
points: 9801000  cells: 19600000
 ━━━━━━━━━━━━━━━━━━━━━━ elapsed: 3s (30.2 it/s)            
vtk mean fps: 60.035830261218564

So there's a factor 2 mismatch...
On top of this vtk 9.0.1 adds another factor 2 apparently because of the `Axes(vtkAssembly)` object ...

**Comment by FedeClaudi** [comment]
I see.. that's a bit confusing..  I was also trying with `plotter.renderer.GetLastRenderTimeInSeconds()` but hadn't done such in dept testing. Thanks for looking into it
