### ISSUE TITLE
using problelines

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#342]
Hi @marcomusy ,
I was going through [this example](https://github.com/marcomusy/vedo/blob/master/examples/volumetric/probeLine2.py) to understand how probe lines can be used to plot the values at points that lie on it.

```
from vedo import *
from vedo.pyplot import plot

vol = load(dataurl+'embryo.slc')
vol.addScalarBar3D(title='wild-type mouse embryo', c='k')

p1, p2 = (50,50,50), (200,200,200)
pl = probeLine(vol, p1, p2, res=100).lineWidth(4)

xvals = pl.points()[:,0]
yvals = pl.getPointArray()
```
Could you please explain 

```
  print(pl.getPointArray()) # numpy scalars can be accessed here
  print(pl.getPointArray('vtkValidPointMask')) # the mask of valid points
```
I could not understand how the valid and invalid points are classified via `pl.getPointArray('vtkValidPointMask')`. Could you please explain this a bit?

**Comment by marcomusy** [comment]
Hi @DeepaMahm 

> `print(pl.getPointArray())`

`pl` is the `vedo.Line` object. This contains point-associated data (each point has a scalar number associated to it). You can access this data via `getPointArray()`. You can get the names of these arrays using eg. `pl.printInfo()`.

> `pl.getPointArray('vtkValidPointMask')`:

 as the line points may not hit the volumetric space defined by the bounding box of `vol`, this will basically give you 1 if the point is inside the volume (so probing it makes sense) otherwise 0.
