### ISSUE TITLE
can i save the outputs that I see visually?

### ISSUE THREAD

**Issue by sahar-github** [marcomusy/vedo#357]
can i save the output results of vedo in any readable format of point clouds (las, ply, obj, off, ...)?

**Comment by sahar-github** [comment]
Thank you for your prompt response

**Comment by sahar-github** [comment]
Actually my question was not very clear.
I have a set of drawings including, mesh, lines, planes, ploygons, graphs
and points which I can see them easily in visualizer.
My purpose is to connect all these seperate objects into one and then write
a file from all as a new mesh/object file.
Could you please let me know how can I do this?
Thanks in advance

**Comment by marcomusy** [comment]
You can use function `merge(myilstofmeshes)` to merge multiple meshes into a single one, but this probably not what you want to do.. If you want to save a whole scene made of multiple objects to file, such file will not be neither `ply` nor `off` because these do not support scenes. So:
- you can save multiple files one for each mesh object and their position in space as ply 
- you can export a whole scene as a numpy object which contains all the info needed by `vedo` to recreate the scene. This is obviously specific to `vedo` but can also be read by other numpy-based applications (this feature is still a bit experimental and might not work perfectly .. but i'm available to improve it if needed). Usage:
`exportWindow("scene.npz")`
`plotter = importWindow("scene.npz")`
Or from command line try eg
`vedo https://vedo.embl.es/examples/geo_scene.npz`

**Comment by sahar-github** [comment]
Thanks 

I need to create a dwg/ dxf format of my results that I can open it later on in Autocad or similar softwar, is it possible to convert .npz to such formats probably?!

I have also another question, which will be very helpful if you could response. AS I mentioned, I have several 3D lines which are the borders of a 3D polygonal shape. But as I used the Line() command, they are disconnected. 
I would like to make a 3d polygon which fits inside these 3d lines/borders, is it something I can try with vedo?
thanks

**Comment by sahar-github** [comment]
another question is how/if I can fit a plane inside a specific border points, 
I already saw there is an example which detects the border points of an existing plane, but how can I fit a plane inside the border points?

I am thinking may be I can fit planes inside the points and then merge all planes as a ply file which I can get usuable output of my data
Is that possible? 
thanks in advace

**Comment by marcomusy** [comment]
> I need to create a dwg/ dxf format of my results that I can open it later on in Autocad or similar softwar, is it possible to convert .npz to such formats probably?!

Sorry VTK does not support (afaik) those formats. You may need to write a converter from ply or numpy to those but I guess that would not be trivial.


> I have also another question, which will be very helpful if you could response. AS I mentioned, I have several 3D lines which are the borders of a 3D polygonal shape. But as I used the Line() command, they are disconnected.
> I would like to make a 3d polygon which fits inside these 3d lines/borders, is it something I can try with vedo?

This sounds possible... You can disregard the lines as such, just take the ordered points and create a new line then you can try e.g.
`line.triangulate()`
or
`line.tomesh()`

> how can I fit a plane **inside** the border points?

what do you mean? You can fit a plane to points with `fitPlane(pts)`
