### ISSUE TITLE
Segmentation in 2D slicing

### ISSUE THREAD

**Issue by FrancoisMasson1990** [marcomusy/vedo#358]
Hello,

Does someone know how we can use vedo sliding 2D (and vtk.vtkImageResliceMapper) to have color segmentation ?
This is an image with what I have in mind.
![image](https://user-images.githubusercontent.com/43648140/113342593-ab66ff80-92fc-11eb-99b7-861288287da7.png)

**Comment by marcomusy** [comment]
Hi Francois, 
at the moment that is not implemented, but it could be an interesting feature, I need to think if it's possible at all to have it included in `vedo`.

**Comment by FrancoisMasson1990** [comment]
Hello Marco

Thanks for your answer. Let me know when you have an update on that topic.

**Comment by marcomusy** [comment]
Hello Francois,
sorry this question slipped off my attention, I'm implementing it because it looks an interesting feature, ..my first try:
![Screenshot from 2021-04-19 17-40-50](https://user-images.githubusercontent.com/32848391/115264251-6c2b1200-a136-11eb-9bde-4bdf0b9a108b.png)

I'll let you know if I can finalize it.

**Comment by marcomusy** [comment]
check out: https://github.com/marcomusy/vedo/blob/master/examples/volumetric/read_volume3.py

![Screenshot from 2021-04-20 22-38-46](https://user-images.githubusercontent.com/32848391/115460984-34e95d80-a229-11eb-9be6-e5f9bfa58084.png)

**Comment by FrancoisMasson1990** [comment]
That's awesome !!
