### ISSUE TITLE
Bending of a Mesh as per Curvature 

### ISSUE THREAD

**Issue by sonumathur** [marcomusy/vedo#496]
can we apply bending or curvature to a mesh as:
![slab](https://user-images.githubusercontent.com/60248559/139190694-efb6fd9f-6114-47cc-8238-0a329258b0f7.jpg)
![slab_bend](https://user-images.githubusercontent.com/60248559/139190710-fd49ec64-391b-4865-b8b1-8a0284e71bce.jpg)

**Comment by marcomusy** [comment]
If you already know the displacements at each vertex you can update the new positions with:
`mesh.points(mesh.points()+displacements)`
If displacements are only known for arbitrary positions in 3d space you can use:
`mesh.warp(sourcepts, targetpts)`
`vedo --search warp`
Otherwise you need to model the deformation by e.g. FEM. The are numerous example in `examples/other/dolfin`.

**Comment by konris87** [comment]
I apologize for bringing this topic back to life. I am wondering if this is possible by attaching the mesh to a curve, such as a Spline. 

Or is there any option to extrude a mesh along a defined Spline?

Kind regards, 
Kostas

**Comment by marcomusy** [comment]
Hi Kostas, I think these two examples can be useful:
`examples/basic/ribbon.py`
`examples/advanced/contours2mesh.py`

**Comment by konris87** [comment]
Thanks a lot for the prompt answer!  :)
