### ISSUE TITLE
Continuous probing of a volume?

### ISSUE THREAD

**Issue by DanKrsi** [marcomusy/vedo#515]
Looking at the probeLine2.py example, I can see that integer values are being obtained from probing the volume object, but how do you get an interpolated value?  What I ultimately want to do is to take a mesh and construct a signed distance volume object. Then, given a set of points, probe the volume object to get an interpolated distance value for each of those points from the original mesh (obviously approx since its through the volume obj).

This feels doable, given that you can construct isosurfaces (with real-number thresholds) from these same volumes.

**Comment by marcomusy** [comment]
They are integers because that specific Volume contains integers, but it may also contain floats.

You can create such volume with `volumeFromMesh()`, see  `examples/volumetric/volumeFromMesh.py`, and
`examples/volumetric/probePoints.py`

> how do you get an interpolated value?

I don't understand what interpolation you need, the one between close-by voxels?

**Comment by DanKrsi** [comment]
Got it! thanks!
