### ISSUE TITLE
I want to access a single face on a mesh object and change its color. Is there a way to do this?

### ISSUE THREAD

**Issue by sherkt1** [marcomusy/vedo#555]
A mesh object is comprised of vertices and a table of vertices for each triangular face. I want to colorize each face one by one.

**Comment by marcomusy** [comment]
You can do:
```python
from vedo import *
import numpy as np

sph = Sphere().lw(1)

colors = np.random.rand(sph.NCells(),3)*255

sph.celldata["face_colors"] = colors.astype(np.uint8)
sph.celldata.select("face_colors")

show(sph, axes=1)
```

<img width="363" alt="Screenshot 2021-12-10 at 00 47 57" src="https://user-images.githubusercontent.com/32848391/145493388-0a53905c-ec5f-409a-b54e-4f43452c0749.png">

**Comment by timeanddoctor** [comment]
Can I take a Gaussian Blur filter or any other smooth for the cell color?

**Comment by marcomusy** [comment]
You can  interpolate the face colors by assigning the colors to the vertices instead of faces. You can achieve this using `mapCellsToPoints()` (try also playing with `settings.interpolateScalarsBeforeMapping = True`).
You cannot "smooth" colors because the `smooth()`method only affects vertex positions.
