### ISSUE TITLE
How to rotate Mesh partly

### ISSUE THREAD

**Issue by s-triar** [marcomusy/vedo#626]
Hey sir.
I want to rotate a tooth in my model.
![image](https://user-images.githubusercontent.com/34316314/163133600-87a20c6a-505a-4f2b-804c-12471dd5b290.png)

but each tooth is connected to the main arch. How can I rotate using mesh.rotate?

I am trying like this
```
def get_label_mesh(self, label):
    model = self.mesh_selected['model']
    mesh = Mesh([model.info['labels'][label]['vertices'], model.info['labels'][label]['cells']])
    return mesh

def pitch(self, rotate_type ):
    mesh = get_label_mesh(self, self.mesh_selected['label'])
    value = +10 if rotate_type=='+' else -10
    print(mesh.polydata())
    mesh.rotateX(value)
    self.model_plot.render()
    print(mesh.polydata())
```

on var `model` in method `get_label_mesh` I get the points and cells from the chosen tooth.
after that, I make them a new Mesh object.

Here I make the application using PyQt5

**Comment by marcomusy** [comment]
> but each tooth is connected to the main arch. How can I rotate using mesh.rotate?

your problem is ill-defined! 

If I understand you have one single mesh with different labels (as pointdata or celldata)... but it's a single object.
What you can do:
- split the mesh with `threshold()`and then rotate any parts independently with `rotate()`, but then the rotated part may overlap the base (arch) and detach from it , which you probably dont like.
- morph the points by defining a set of displacements for the points that you want to move and the ones that y wish stay fixed, you can do this with class method `warp()` or with some other finite element method e.g. [dolfin](https://github.com/marcomusy/vedo/blob/master/examples/other/dolfin/ex06_elasticity2.py).

**Comment by s-triar** [comment]
Yeah sorry for my knowledge regarding the issue.

I found that the second option is suitable for what I want.

**Comment by kkline2019** [comment]
I'm having a related issue I'm trying to create a rotation animation of a propeller blade but when it keeps rotating in a circle is there a way to have an object rotate on a fixed point or at the very least reduce the rotation radius
