### ISSUE TITLE
Vedo closing PySide2 window on close

### ISSUE THREAD

**Issue by jackson-ua** [marcomusy/vedo#636]
As title says, I have a PySide2 GUI that triggers code to display a point cloud using the Vedo show() function. I call show() on a list of Vedo point objects.

With or without the .close() after .show(), when the Vedo point cloud display is closed, all other active windows close with it. No error message is displayed

**Comment by marcomusy** [comment]
sorry for the late reply, you may need to provide a minimal script to allow reproducing the issue, have you tried calling
`plt.interactor.Start()`

**Comment by vene** [comment]
I think I'm seeing the same issue or a related one: I tried running several of the bundled examples and the plotted window is instantly closed before i have a chance to interact with it.

`interactive=True` makes no difference.

On my system this happens when I run any of the following commands:

```
vedo -r plot_errbars
vedo -r histo_polar
vedo -r histo_spheric
```
I assume it just happens for any vedo plot.

I have python 3.10.4, vtk==9.2.0rc1, numpy==1.21.6.
