### ISSUE TITLE
Problem on mesh to PointsLoop

### ISSUE THREAD

**Issue by Eva-xx** [marcomusy/vedo#698]
Hi！Thank you so much for your work! He facilitated my research a lot. But I have two questions I would like your help with. 
I use the function intersectWith to calculate the intersection of two meshes, and I want to use the intersection to clip the two meshes, but the result returned by intersectWith is a mesh instead of a loop, how can I do the type conversion? 
In addition, I am very curious why after performing a Boolean operation on two intersecting meshes, their intersection is still the boundary of the result. According to my understanding, the closed mesh obtained by the Boolean operation should have no boundary.
Very much looking forward to your reply.

**Comment by marcomusy** [comment]
Hi I'm happy that you find it useful!
maybe you don't need to use a loop to cut it, you can cut a mesh directly with another with `cutWithMesh()`
https://vedo.embl.es/autodocs/content/vedo/pointcloud.html#vedo.pointcloud.Points.cutWithMesh

The output of `intersectWith()` is still a mesh because in the general case the intersection can give multiple disconnected  lines. For simpler cases you can obtain an ordered line by calling `.join(reset=True)`.

The boolean operation is not working perfectly in all cases, but it requires that the surfaces are closed.
Hope this helps.

**Comment by Eva-xx** [comment]
Thank you very much for your reply!
I've tried using this function cutWithMesh() before, but it turned out to be a little weird.
In the figure the green and yellow are two meshes, respectively. From the intersecting lines everything looks fine. 
![image](https://user-images.githubusercontent.com/56378463/192125990-0600a163-14cd-418a-9da3-29518875c506.png)
But when I use this function cutWithMesh() , the result is not what I expected.
![image](https://user-images.githubusercontent.com/56378463/192125917-c525f5cd-9227-4b70-a7bb-9d6af075912f.png)
Do you have any good suggestions?

**Comment by marcomusy** [comment]
I guess the issue is the bottom right corner...
It looks to me that it can be caused by a wrong oriented normal in the green mesh.
One possibility is to recreate the mesh and recompute normals:
```
new_green_mesh = Mesh([old_mesh.points(), old_mesh.faces()]).computeNormals()
```
you can also manually edit the small imperfection with class
```
from vedo.applications import FreeHandCutPlotter
```
or interactively with command line e.g.:
```
vedo -e mymesh.stl
```

**Comment by Eva-xx** [comment]
Great! 
I rechecked my meshes. As you can guess, the mesh is of poor quality and too dense in places. After I create a uniformly meshed surface using voronoi clustering, the function cutWithMesh() works just fine! Thanks again for your reply!
