### ISSUE TITLE
incorrect color to display vtu file

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#834]
I have a `vtu` file, and `vedo` show it as:

![image](https://user-images.githubusercontent.com/29271051/226098618-1b5ab706-02eb-4f93-b4a4-b882dfe4bd30.png)

In this figure, the red color indicate lower value than blue color, which is non-instinctive. Is it possible to make red color indicate the higher value?

The test data is:

[flow.zip](https://github.com/marcomusy/vedo/files/11008192/flow.zip)

**Comment by zhang-qiang-github** [comment]
In addition, when I set the color map to `rainbow`, the colorbar is weird.

```
mesh = Mesh('C:\\Users\\Administrator\\Desktop\\SU2-v7.5.1-win64\\bin\\Vessel\\flow.vtu').add_scalarbar('pressure').cmap('rainbow')

show(mesh)
```

The result is:

![image](https://user-images.githubusercontent.com/29271051/226101200-c2005ec0-9b19-46cb-b2d9-55276d174d5d.png)

The colorbar is not continuous. Why?

**Comment by marcomusy** [comment]
that's because you added the scalar bar before the cmap call (so you are actually mapping some other vector), try
```python
from vedo import * 
tmsh = TetMesh("mega/vedo_data/flow.vtu")
msh = tmsh.tomesh(fill=False)
msh.cmap("rainbow", "Pressure").add_scalarbar()
show(msh, axes=1)
```
<img width="343" alt="Screenshot 2023-03-18 at 15 34 32" src="https://user-images.githubusercontent.com/32848391/226112737-12c00df9-c2fb-49eb-8dca-d1374b7ea8bb.png">

you can invert any colormap name by adding `_r`, e.g. `"rainbow_r"`
