### ISSUE TITLE
Crop a mesh with bounds param

### ISSUE THREAD

**Issue by fperezNem** [marcomusy/vedo#847]
In the crop function for meshes, until version 2022.4.1, the bounds parameter could be used. This way you could get the crop at a specific point. Now it is only allowed to make a percentage, isn't there another way to get the crop with the bounds again?

**Comment by marcomusy** [comment]
Hi, I think I removed that because in principle you may use the `cut_with_box()` method...
https://vedo.embl.es/autodocs/content/vedo/vedo/pointcloud.html#Points.cut_with_box

Check also
https://vedo.embl.es/autodocs/content/vedo/vedo/pointcloud.html#Points.cut_with_plane
https://vedo.embl.es/autodocs/content/vedo/vedo/pointcloud.html#Points.cut_with_planes
