### ISSUE TITLE
`distance_to` function to return id of nearest vertex?

### ISSUE THREAD

**Issue by jo-mueller** [marcomusy/vedo#885]
Hi @marcomusy ,

I'm playing a bit with the `distance_to` function to calculate vertex-wise distances to a second mesh. I was wondering whether it were possible to return - aside from the distance to the second mesh - the id of the respective corresponding vertex in the second mesh?

In other words (hope it makes sense what I'm writing ^^") - I'd hope to get, for any vertex in a `mesh A`, to get the distance to `mesh B` and the identity of the vertex in `mesh B` that's closest to the respective vertex in `mesh A`. Or would I simply do this with a for loop over all the vertices in `mesh A`, querying for the nearest neighbor in `mesh B` with the `closest_point()` function? 

Thanks!

**Comment by marcomusy** [comment]
Hi, 
the `distance_to` returns the distance to closest point _on the mesh_, which can be a point on any of the triangular faces.
If you are querying distances of pointclouds you can still use `distance_to` but if you want the ids it's easier if you do it with `closest_point(return_point_id=True)` in a loop. this should be fast because under the hood a kdtree is built.
